/**
 * Auto-generated by `npm run sync:dieu-khoan`.
 * Source of truth: Google Doc (see sourceDocUrl).
 * Do not edit body by hand — re-run the sync script instead.
 */

export type DieuKhoanThamGiaContent = {
  title: string;
  subtitle: string;
  body: string;
  sourceDocUrl: string;
  lastSyncedAt: string;
  isDraft: boolean;
};

export const dieuKhoanThamGiaContent: DieuKhoanThamGiaContent = {
  title: `ĐIỀU KHOẢN THAM GIA DỰ ÁN NUÔI EM - NĂM HỌC 2026-2027`,
  subtitle: `(Áp dụng đối với tất cả Anh/Chị nuôi tham gia Dự án Nuôi em từ năm học 2026–2027)`,
  body: `# ĐIỀU KHOẢN THAM GIA DỰ ÁN NUÔI EM - NĂM HỌC 2026-2027

(Áp dụng đối với tất cả Anh/Chị nuôi tham gia Dự án Nuôi em từ năm học 2026–2027)

## Điều 1. Mục tiêu của Dự án Nuôi em

Dự án Nuôi em do CTCP Doanh nghiệp xã hội Quỹ Nuôi em vận hành nhằm kết nối, huy động nguồn lực xã hội để hỗ trợ học sinh vùng khó khăn, góp phần duy trì việc đến trường, cải thiện điều kiện học tập và nâng cao chất lượng cuộc sống của các em.

Hoạt động trọng tâm của Dự án là hỗ trợ chi phí bữa ăn bán trú cho học sinh. Bên cạnh đó, trong phạm vi nguồn lực của Dự án, Dự án có thể triển khai các hoạt động hỗ trợ khác như hỗ trợ giáo viên tham gia tổ chức bữa ăn hoặc các hoạt động hỗ trợ khác phù hợp với mục tiêu của Dự án.

Dự án Nuôi Em tin rằng mỗi khoản tài trợ là sự gửi gắm niềm tin của Anh/Chị nuôi  dành cho học sinh vùng khó khăn. Điều khoản này được xây dựng nhằm bảo đảm mọi khoản tài trợ được quản lý công khai, minh bạch, sử dụng đúng mục đích và giúp Dự án vận hành hiệu quả, bền vững vì lợi ích của các em học sinh. Việc Anh/Chị nuôi  tham gia Dự án đồng nghĩa với việc đã đọc, hiểu và đồng ý toàn bộ các điều khoản dưới đây.

## Điều 2. Đăng ký tham gia

2.1. Anh/Chị nuôi (sau đây gọi tắt là ACN) thực hiện đăng ký trên website chính thức của Dự án Nuôi em: https://quynuoiem.com/

2.2. ACN cung cấp đầy đủ, trung thực các thông tin theo yêu cầu, bao gồm tối thiểu:

- Họ và tên

- Số điện thoại;

- Email (nếu có);

- Các thông tin cần thiết khác phục vụ quản lý.

2.3. Sau khi hoàn tất đăng ký trên website, Dự án Nuôi em sẽ cấp cho mỗi Anh/Chị Nuôi một Mã Anh/Chị nuôi (Mã ACN) duy nhất.

Ví dụ: ACN00001

Mã ACN được sử dụng để định danh ACN trong toàn bộ quá trình tham gia Dự án và được giữ nguyên trong các năm học tiếp theo, trừ trường hợp có điều chỉnh do lỗi dữ liệu hoặc theo quyết định của Dự án.

2.4. Mã ACN không đồng nghĩa với việc đã hoàn tất việc nhận nuôi. Việc nhận nuôi chỉ được xác nhận sau khi Dự án ghi nhận khoản tài trợ hợp lệ theo quy định.

## Điều 3. Thời gian tiếp nhận đăng ký và tài trợ

3.1. Đối với năm học 2026–2027, Dự án tiếp nhận đăng ký và nhận tài trợ trong thời gian từ ngày 01/08/2026 đến hết ngày 31/12/2026.

3.2. ACN thực hiện thanh toán 01 (một) lần để hoàn thành khoản tài trợ của năm học, thông tin tài khoản như sau:

Số tài khoản: 1805

Ngân hàng: Ngân hàng thương mại cổ phần Quân đội (MB)

Chủ tài khoản: CÔNG TY CỔ PHẦN DOANH NGHIỆP XÃ HỘI QUỸ NUÔI EM

3.3. Khi thực hiện chuyển khoản, ACN ghi đúng Mã ACN vào nội dung chuyển khoản theo cú pháp do Dự án hướng dẫn để phục vụ việc đối soát và ghi nhận khoản tài trợ. Trường hợp ACN chuyển khoản thành công nhưng quên ghi hoặc ghi không đúng Mã ACN trong nội dung chuyển khoản, ACN cần chủ động thông báo cho Dự án trong thời gian sớm nhất và cung cấp ảnh chụp hoặc chứng từ giao dịch thành công để Dự án thực hiện đối soát và cập nhật thông tin trên hệ thống.

3.4. Đối với các khoản tài trợ có giá trị lớn hoặc theo nhu cầu của cá nhân, tổ chức, Dự án và bên tài trợ có thể ký kết Thỏa thuận tài trợ hoặc văn bản thỏa thuận riêng nhằm quy định cụ thể về mục tiêu tài trợ, phương thức triển khai, chế độ báo cáo, quyền và nghĩa vụ của các bên, trên cơ sở phù hợp với Điều khoản tham gia này và quy định của pháp luật.

3.5. Theo yêu cầu của ACN, Dự án có thể cấp Thư cảm ơn, Giấy xác nhận tài trợ hoặc các văn bản xác nhận khác trong phạm vi chức năng của Dự án để phục vụ nhu cầu lưu trữ hồ sơ, kế toán hoặc thực hiện các thủ tục theo quy định của pháp luật.

## Điều 4. Mức tài trợ

Mức tài trợ tại khu vực Phía Bắc:

- Học sinh ăn 01 bữa/ngày: 170.000 đồng/tháng × 09 tháng = 1.530.000 đồng/học sinh/năm học.

- Học sinh ăn 02 bữa/ngày: 340.000 đồng/tháng × 09 tháng = 3.060.000 đồng/học sinh/năm học.

(Đối với học sinh ăn 02 bữa/ngày (bữa trưa và bữa tối), mức tài trợ được tính bằng 02 lần mức tài trợ của học sinh ăn 01 bữa/ngày do chi phí bữa ăn được hỗ trợ gấp đôi)

Mức tài trợ có thể được tài trợ theo từng năm học hoặc theo số tháng ăn, căn cứ vào tình hình thực tế, chi phí tổ chức bữa ăn và nguồn lực huy động. Mọi thay đổi sẽ được Dự án công bố công khai trước thời điểm bắt đầu tiếp nhận tài trợ của năm học tương ứng.

## Điều 5. Nguyên tắc quản lý và sử dụng nguồn tài trợ

5.1. Khi đăng ký tham gia Chương trình, ACN đăng ký số lượng học sinh hoặc số suất hỗ trợ mong muốn đồng hành trong năm học, không đăng ký một học sinh cụ thể.

5.2. Sau khi Dự án tiếp nhận khoản tài trợ hợp lệ và kết thúc từng kỳ tổng hợp nguồn lực, Dự án sẽ xây dựng kế hoạch triển khai tại các trường và thực hiện phân bổ nguồn tài trợ theo nhu cầu thực tế, bảo đảm phù hợp với mục tiêu của Dự án.

Ví dụ:

- ACN đăng ký và hoàn thành tài trợ bắt đầu từ tháng 08/2026

- Dự án chốt số liệu vào ngày 25/08/2026;

- Căn cứ số tiền đã tiếp nhận, Dự án thông báo cho các trường đủ điều kiện để thông báo và ký thỏa thuận với Nhà trường để tổ chức bữa ăn cho các em học sinh bắt đầu từ tháng 09/2026.

5.3. ACN đồng ý rằng khoản tài trợ được quản lý theo quỹ chung của Dự án và được phân bổ cho các trường, học sinh thuộc đối tượng hỗ trợ theo kế hoạch triển khai. Việc phân bổ không phụ thuộc vào một học sinh cụ thể tại thời điểm ACN đăng ký hoặc chuyển khoản.

5.4. Sau khi hoàn thành việc rà soát, đối soát và phân bổ tại các trường, Dự án sẽ ghép thông tin học sinh đồng hành với ACN theo quy định tại Điều 6.

5.5. Việc điều chuyển, thay đổi hoặc cập nhật thông tin học sinh đồng hành (nếu có) không làm thay đổi mục đích sử dụng khoản tài trợ của ACN, miễn là khoản tài trợ vẫn được sử dụng đúng cho các đối tượng thuộc phạm vi của Dự án Nuôi em.

## Điều 6. Cung cấp thông tin học sinh đồng hành

6.1. Việc ghép thông tin học sinh với ACN được thực hiện sau khi Dự án hoàn thành việc rà soát danh sách học sinh thuộc diện hỗ trợ tại từng trường.

6.2. Đối với các khoản tài trợ được ghi nhận trước ngày 31/11/2026, thông tin học sinh đồng hành sẽ được cung cấp từ tháng 11/2026 sau khi Dự án hoàn tất việc đối soát và phân bổ.

6.3. Đối với các khoản tài trợ được ghi nhận từ ngày 01/12/2026 đến hết ngày 31/12/2026, thông tin học sinh đồng hành dự kiến sẽ được cập nhật trong thời hạn 07 ngày làm việc kể từ ngày Dự án  Nuôi em xác nhận đã nhận đủ khoản tài trợ.

6.4. Thông tin học sinh đồng hành có thể thay đổi trong quá trình thực hiện Dự án nếu học sinh không còn thuộc đối tượng hỗ trợ hoặc phát sinh các lý do khách quan khác. Trong trường hợp đó, Dự án Nuôi em sẽ điều chuyển ACN sang đồng hành với học sinh khác có hoàn cảnh tương đương đúng mục tiêu của dự án.

## Điều 7. Giải ngân

Dự án Nuôi em thực hiện giải ngân theo từng đợt căn cứ vào đề nghị thanh toán của nhà trường. Đối với năm học 2026–2027 dự kiến gồm 4 đợt, các đợt giải ngân gồm:

- Tháng 11/2026;

- Tháng 01/2027;

- Tháng 03/2027;

- Tháng 06/2027.

Lịch giải ngân có thể được điều chỉnh phù hợp với tình hình thực tế nhưng vẫn bảo đảm đúng mục đích sử dụng nguồn tài trợ.

## Điều 8. Quản lý số tiền tài trợ

Trong thời gian khoản tài trợ chưa đến kỳ giải ngân, Anh/chị nuôi cho phép Dự án gửi số tiền gửi tại ngân hàng. Khoản tài trợ gốc của ACN được bảo toàn và chỉ được sử dụng đúng mục đích hỗ trợ học sinh theo Điều khoản tham gia và Quy chế quản lý tài chính của Dự án. Khoản lãi phát sinh từ việc quản lý số dư tiền tài trợ (nếu có) được hạch toán riêng và sử dụng cho các chi phí quản lý, vận hành của Dự án theo quy định tại Điều này, bao gồm nhưng không giới hạn ở:

- Chi phí vận hành hệ thống công nghệ và quản trị dữ liệu;

- Chi phí nhân sự, cộng tác viên trực tiếp tham gia vận hành dự án;

- Các khoản phải nộp nhà nước;

- Chi phí Kiểm toán hàng năm

- Chi phí ngân hàng;

- Các chi phí khác dùng cho hoạt động vận hành của Dự án.

ACN đồng ý với nguyên tắc này khi tham gia Dự án.

## Điều 9. Báo cáo và minh bạch

9.1. ACN có quyền theo dõi thông tin khoản tài trợ thông qua website hoặc các kênh thông tin chính thức của Dự án.

9.2. Dự án thực hiện công khai các thông tin phù hợp với quy định của pháp luật và quy chế nội bộ, bao gồm:

- Số lượng học sinh được hỗ trợ;

- Danh sách trường tham gia;

- Sao kê tài khoản tiếp nhận tài trợ và tình hình giải ngân;

- Báo cáo tài chính và báo cáo hoạt động của Dự án;

- Các thông tin, hình ảnh và báo cáo liên quan đến việc triển khai Dự án.

## Điều 10. Thăm học sinh đồng hành

Hằng năm Dự án dự kiến tổ chức hai đợt thăm học sinh (Tháng 11-12/2026 và Tháng 03-04/2027). ACN có thể đăng ký tham gia trên tinh thần tự nguyện. Chi phí đi lại, ăn ở và các chi phí phát sinh do ACN tự chi trả. Dự án có trách nhiệm kết nối giữa ACN với Nhà trường để ACN được thăm đúng em học sinh mà mình đã nhận nuôi.

## Điều 11. Hoàn trả tài trợ

11.1. Khoản tài trợ chỉ được xem xét hoàn trả trong các trường hợp:

- Giao dịch chuyển nhầm;

- Lỗi kỹ thuật của hệ thống;

- Các trường hợp phát sinh do lỗi của Dự án dẫn đến việc ghi nhận hoặc xử lý khoản tài trợ không đúng.

11.2. Đối với các trường hợp quy định tại khoản 11.1, ACN cần chủ động liên hệ ngân hàng nơi thực hiện giao dịch để đề nghị tra soát theo quy trình của ngân hàng, đồng thời thông báo cho Dự án để phối hợp đối chiếu và xử lý khi cần thiết.

11.3. Sau khi ACN đã đồng ý tham gia Chương trình và khoản tài trợ đã được Dự án ghi nhận, phân bổ hoặc sử dụng để triển khai tại nhà trường, Dự án không thực hiện hoàn trả theo yêu cầu thay đổi của ACN, trừ hợp pháp luật có quy định khác hoặc thuộc các  trường hợp quy định tại khoản 11.1 Điều này.

## Điều 12. Công bố và bảo mật thông tin

12.1. Dự án cam kết quản lý, lưu trữ và sử dụng thông tin cá nhân của Anh/Chị nuôi theo quy định của pháp luật và Chính sách bảo vệ dữ liệu cá nhân của Dự án.

12.2. Thông tin ACN được sử dụng cho các mục đích sau:

- Xác nhận và quản lý khoản tài trợ;

- Liên hệ trong quá trình triển khai Dự án;

- Cập nhật thông tin học sinh đồng hành;

- Gửi báo cáo, thư cảm ơn, giấy xác nhận tài trợ và các thông tin liên quan đến Dự án;

12.3. Dự án không công khai số điện thoại, địa chỉ, email hoặc các thông tin cá nhân khác của ACN cho bên thứ ba, trừ trường hợp pháp luật có quy định hoặc được ACN đồng ý.

12.4. ACN đồng ý để Dự án cung cấp cho nhà trường và giáo viên phụ trách các thông tin cần thiết phục vụ việc tri ân và kết nối, bao gồm:

- Họ và tên hoặc tên hiển thị do ACN đăng ký;

- Mã ACN

- Số lượng học sinh hoặc số suất ăn tài trợ.

12.5. Trường hợp ACN không mong muốn công khai họ tên trong các tài liệu tri ân, ACN có thể lựa chọn hiển thị theo tên viết tắt, biệt danh hoặc mã ACN theo chức năng được Dự án cung cấp.

12.6. Thông tin, hình ảnh và dữ liệu của học sinh được Dự án cung cấp cho ACN chỉ nhằm mục đích theo dõi, đồng hành và lưu giữ kỷ niệm. ACN cam kết không sử dụng các thông tin này vào mục đích thương mại, không đăng tải hoặc chia sẻ làm ảnh hưởng đến quyền, lợi ích hợp pháp, danh dự và quyền riêng tư của học sinh nếu chưa được người đại diện hợp pháp của học sinh cho phép.

## Điều 13: Cam kết của Dự án

13.1. Dự án cam kết tiếp nhận, quản lý và sử dụng các khoản tài trợ đúng mục đích, phù hợp với Điều khoản tham gia, Quy chế quản lý tài chính của Dự án và quy định của pháp luật.

13.2. Dự án thực hiện quản lý nguồn tài trợ theo nguyên tắc công khai, minh bạch, hiệu quả và ưu tiên tối đa lợi ích của học sinh thuộc đối tượng hỗ trợ.

13.3. Dự án có trách nhiệm thực hiện việc phân bổ, giải ngân, theo dõi và báo cáo tình hình sử dụng nguồn tài trợ theo quy định của Dự án.

13.4. Dự án bảo đảm thông tin cá nhân của ACN và thông tin của học sinh được quản lý, lưu trữ và sử dụng theo quy định của pháp luật.

## Điều 14: Trường hợp bất khả kháng

Trong trường hợp bất khả kháng như: thiên tai, dịch bệnh, chiến tranh, thay đổi chính sách Nhà nước, các trường hợp bất khả kháng khác,... làm ảnh hưởng đến việc triển khai Dự án, Dự án sẽ điều chỉnh kế hoạch thực hiện, thời gian giải ngân hoặc phương thức hỗ trợ nhằm bảo đảm mục tiêu chung của Dự án và sẽ thông báo ACN trên các kênh chính thức.

## Điều 15. Đồng ý của Anh/Chị nuôi

Bằng việc ghi "Tôi đã đọc và đồng ý với Điều khoản tham gia Dự án Nuôi Em" và thực hiện thanh toán, ACN xác nhận rằng:

1. Đã đọc và hiểu đầy đủ các điều khoản của Dự án;

2. Đồng ý để khoản tài trợ được quản lý theo nguyên tắc của Dự án;

3. Đồng ý việc thông tin học sinh đồng hành có thể được công bố sau thời điểm thanh toán và có thể thay đổi theo tình hình thực tế nhưng vẫn đảm bảo khoản tài trợ được thực hiện đúng theo mục đích của Dự án.

4. Đồng ý để Dự án quản lý số dư tiền tài trợ và sử dụng khoản lãi phát sinh theo quy định tại Điều 8;

5. Cam kết không có khiếu nại liên quan đến việc phân bổ học sinh hoặc điều chuyển học sinh trong phạm vi Dự án khi việc điều chuyển được thực hiện đúng các điều khoản này.

Điều khoản tham gia này có hiệu lực kể từ ngày 01/08/2026 và áp dụng đối với tất cả Anh/Chị nuôi tham gia Dự án Nuôi Em từ năm học 2026–2027 cho đến khi được sửa đổi, bổ sung hoặc thay thế bằng văn bản mới.

Xin chân thành cảm ơn Anh/Chị đã tin tưởng, đồng hành cùng Dự án Nuôi Em. Mỗi khoản tài trợ không chỉ góp phần mang đến những bữa ăn đủ đầy cho học sinh vùng khó khăn mà còn tiếp thêm động lực để các em vững bước đến trường.

Trân trọng!

CTCP Doanh nghiệp xã hội Quỹ Nuôi Em`,
  sourceDocUrl: "https://docs.google.com/document/d/11bNkU9NKZFzDTte2eExnJVcEB3r178Uk9eZ8xgvslMg/edit?usp=sharing",
  lastSyncedAt: "2026-08-05T12:35:20.436Z",
  isDraft: true,
};
